name: SSH-Docker Compose
description: SSH into host and deploy repository with Docker Compose V2
branding:
  icon: server
  color: purple
inputs:
  ssh_private_key:
    description: Private SSH key used for logging into remote system.
    required: true
  ssh_host:
    description: Remote host name or IP.
    required: true
  ssh_port:
    description: Remote SSH port.
    default: 22
    required: true
  ssh_user:
    description: Remote user name.
    required: true
  workspace:
    description: Remote workspace.
    default: 'workspace'
    required: false
  docker_compose_filename:
    description: Docker compose file to use, defaults to docker-compose.yaml
    default: docker-compose.yaml
    required: false
  docker_compose_down:
    description: Execute docker compose-down ("true" or "false").
    default: 'false'
    required: false
runs:
  using: docker
  image: Dockerfile
  env:
    SSH_USER: ${{ inputs.ssh_user }}
    SSH_HOST: ${{ inputs.ssh_host }}
    SSH_PORT: ${{ inputs.ssh_port }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
    WORKSPACE: ${{ inputs.workspace}}
    DOCKER_COMPOSE_FILENAME: ${{ inputs.docker_compose_filename }}
    DOCKER_COMPOSE_PREFIX: ${{ inputs.docker_compose_prefix }}
    DOCKER_COMPOSE_DOWN: ${{ inputs.docker_compose_down }}
